variable "vpc_cidr_block" {
  description = "Map o CIDRs for environments"
  type        = map(string)
  default = {
    develop     = "189.39.0.0/16"
    homolog     = "173.83.0.0/16"
    production  = "128.21.0.0/16"
    engineering = "191.33.0.0/16"
  }
}

variable "zone_numbers" {
  description = "Number of availability zones used"
  type        = number
  default     = 2
}

variable "aws_profile" {
  description = "The profile with aws credentials to run terraform"
  type        = string
  default     = "usp-adm"
}

variable "ssh_key_path" {
  type        = string
  description = "Save location for ssh public keys generated by the module"
}

variable "generate_ssh_key" {
  type        = bool
  description = "Whether or not to generate an SSH key"
}

variable "region" {
  type        = string
  description = "AWS region"
  default     = "us-east-1"
}

variable "instance_type" {
  type        = string
  default     = "t2.micro"
  description = "Bastion instance type"
}

variable "security_group_rules" {
  type        = list(any)
  description = <<-EOT
    A list of maps of Security Group rules. 
    The values of map is fully complated with `aws_security_group_rule` resource. 
    To get more info see https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule .
  EOT
}

variable "associate_public_ip_address" {
  type        = bool
  default     = true
  description = "Whether to associate public IP to the instance."
}